[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef
GROQ = "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" # Groqkp API key - gsk_1234567890abcdef1234567890abcdef
ANTHROPIC = "" # Anthropic API key - sk-ant-1234567890abcdef1234567890abcdef

[API_ENDPOINTS]
SEARXNG = "https://konectunalanda.in" # SearxNG API URL
OLLAMA = "" # Ollama API URL - http://host.docker.internal:11434


